### ISSUE TITLE
`no-implicit-any-catch` throws an error

### ISSUE THREAD

**Issue by cerealcable** [cartant/eslint-plugin-rxjs#122]
When `no-implicit-any-catch` encounters a `catchError` statement without any types we end up getting an error. See https://github.com/cartant/eslint-plugin-etc/issues/63 as this happens in this repository as well.

It appears https://github.com/cartant/eslint-etc/pull/12 fixes the problem for us. Hoping we could get a review and merge on that PR? Once I used the contents of that PR it resolved this error for us. We'd like to enable the `no-implicit-any-catch` rule but need this merged to do so.

**Comment by sjarva** [comment]
We have a similar situation, but I'd like to add that even with a disabling comment for this `no-implicit-any-catch` rule, eslint lint process is stopped by an exception/error. This is really inconvenient because we have already enabled this rule and in some cases we have had to use the disabling comment, and now the exception/error breaks our lint, which is one step in our CI/CD. So we had to turn this rule off while we wait for a fix.

**Comment by gultyayev** [comment]
Could you create a snippet that can reproduce the error? As small as possible.
I'm trying to create a test case that would fail on the error, but somehow it doesn't fail with the error 😮 
```typescript
// tap; arrow; implicit option
import { throwError } from "rxjs";
import { tap } from "rxjs/operators";

throwError("Kaboom!").pipe(tap({
  next: () => {},
  error: err => {},
}));
```

**Comment by merkuriy** [comment]
We have a similar situation. We had to turn this rule off while we wait for a fix.

Example:
```ts
of(1).pipe(
    catchError((err) => {
        return of(2);
    }),
);
```

Log:
```log
TypeError: Cannot read properties of undefined (reading 'typeAnnotation')
Occurred while linting ./src/file.ts:11
Rule: "rxjs/no-implicit-any-catch"
    at checkCallback (./node_modules/eslint-plugin-rxjs/dist/rules/no-implicit-any-catch.js:60:59)
    at CallExpression[callee.name='catchError'] (./node_modules/eslint-plugin-rxjs/dist/rules/no-implicit-any-catch.js:126:17)
    at ruleErrorHandler (./node_modules/eslint/lib/linter/linter.js:1076:28)
    at ./node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (./node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (./node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (./node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (./node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:803:23)
```

**Comment by vladkasianenko** [comment]
Have the same issue:
![image](https://github.com/cartant/eslint-plugin-rxjs/assets/14053728/b540ece0-851e-41c1-ab77-1f10ca8eac9c)

Even if I do `// eslint-disable-next-line rxjs/no-implicit-any-catch` or /* eslint-disable rxjs/no-implicit-any-catch */ at the top of file, I still have this error.

The only solution for me is to set it to `off` in the .eslintrc file.

**Comment by meet-ben** [comment]
Same issue here:

```
TypeError: Cannot destructure property 'typeAnnotation' of 'typeAnnotation' as it is undefined.
Occurred while linting D:\git\company\project\libs\channel\channel-integration\feature-manage\src\lib\channel-integration-form\channel-integration-form.component.ts:275
Rule: "rxjs/no-implicit-any-catch"

TypeError: Cannot destructure property 'typeAnnotation' of 'typeAnnotation' as it is undefined.
Occurred while linting D:\git\company\project\libs\channel\channel-integration\feature-manage\src\lib\channel-integration-form\channel-integration-form.component.ts:275
Rule: "rxjs/no-implicit-any-catch"
    at checkCallback (D:\git\company\project\node_modules\.pnpm\eslint-plugin-rxjs@5.0.3_eslint@8.57.0_typescript@5.7.3\node_modules\eslint-plugin-rxjs\dist\rules\no-implicit-any-catch.js:60:45)
    at CallExpression[callee.property.name='subscribe'],CallExpression[callee.name='tap'] (D:\git\company\project\node_modules\.pnpm\eslint-plugin-rxjs@5.0.3_eslint@8.57.0_typescript@5.7.3\node_modules\eslint-plugin-rxjs\dist\rules\no-implicit-any-catch.js:142:25)
    at ruleErrorHandler (D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\linter.js:1076:28)
    at D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (D:\git\company\project\node_modules\.pnpm\eslint@8.57.0\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:803:23)
```

**Comment by JasonWeinzierl** [comment]
There are several active forks which all fix this bug:

- [eslint-plugin-rxjs-x](https://www.npmjs.com/package/eslint-plugin-rxjs-x)
- [@smarttools/eslint-plugin-rxjs](https://www.npmjs.com/package/@smarttools/eslint-plugin-rxjs)
- ~[eslint-plugin-rxjs-updated](https://www.npmjs.com/package/eslint-plugin-rxjs-updated)~ it looks like fast-facts has archived their fork repo and started using `eslint-plugin-rxjs-x` internally

**Comment by Hypenate** [comment]
It crashes when there is no **type** set.
This gives the error:
```
of(1).pipe(catchError((err) => return of(2)));
```

This does not:
```
of(1).pipe(catchError((err: unknown) => return of(2)));
```
